linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  fast: false